name: tpms_app
description: A Flutter TPMS application with BLE sensor integration.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.3.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/wheels_india_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
